version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb:/data/db
    networks:
      - tg-bot-network

  tg-bot:
    build: .
    volumes:
      - ./app:/app
    command: python main.py
    networks:
      - tg-bot-network

networks:
  tg-bot-network: